# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: enol.fernandez@egi.eu
author_name: Enol Fernandez
has_binder: false
has_settings: false
kind: frontend
labextension_name: resource_warning
project_short_description: A JupyterLab extension.
python_name: resource_warning
repository: https://github.com/enolfc/resource-warnings
test: false

